### ISSUE TITLE
it is not good support for chinese, and so other language. I think it must get the length of string is wrong

### ISSUE THREAD

**Issue by fengbenming** [bndr/gotabulate#11]
+-------------------------+-------------------------+-------------+-----------------------+-----------------------+-----------------------+
| 前10产品销量比    | 前10品牌销量比    | 销量      | 销售的产品数    | 销售的品牌数    | 销售的分类数    |
+=========================+=========================+=============+=======================+=======================+=======================+
| 0.64                    | 0.68                    | 3173299     | 2690                  | 153                   | 109                   |
+-------------------------+-------------------------+-------------+-----------------------+-----------------------+-----------------------+
| 0.68                    | 0.58                    | 26524137    | 5326                  | 236                   | 350                   |
+-------------------------+-------------------------+-------------+-----------------------+-----------------------+-----------------------+

**Comment by fengbenming** [comment]
the header is not align with the field

**Comment by huanlingkeji** [comment]
![image](https://user-images.githubusercontent.com/43662114/76595482-ad65f100-6536-11ea-95bb-df1c7fd15e46.png)
![image](https://user-images.githubusercontent.com/43662114/76595542-d5555480-6536-11ea-9b4c-e446ac1d2898.png)

![image](https://user-images.githubusercontent.com/43662114/76595505-bfe02a80-6536-11ea-9577-11859354df0c.png)
try as this

**Comment by SherLockOD** [comment]
The master branch has fixed this problem.
